spring:
  datasource:
    hikari:
      spring.jpa.show-sql: true
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/test
      username: test
      password: test
      maximum-pool-size: 80
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
mybatis:
  type-alias-package: com.sbtest.dto
  mapper-locations: classpath:mapper/*.xml
  config-location: mybatis-config.xml
server:
  port: 8080
