spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    hikari:
      spring.jpa.show-sql: true
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/test
      username: test
      password: test
      maximum-pool-size: 80
      connectionTimeout: 30000
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: mybatis-config.xml
logging:
  pattern:
   console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:Line %line] - %msg%n"
  level:
    org.springframework.web: DEBUG
    com.sbtest: DEBUG
server:
  port: 8080
